
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-w24/team03-w24-5pm-3
owner: ucsb-cs156-w24
repo_name: team03-w24-5pm-3
pull_requests: [{"author":{"id":"U_kgDOBXv56g","is_bot":false,"login":"sophiattran","name":""},"headRefName":"Sophia-MenuItemReviews-backend","number":67,"title":"Sophia MenuItemReviews - Copied all backend code files from team02","url":"https://github.com/ucsb-cs156-w24/team03-w24-5pm-3/pull/67"},{"author":{"id":"MDQ6VXNlcjc5MzcxNjc1","is_bot":false,"login":"theanimated01","name":"Animesh Sachan"},"headRefName":"as-Articles-table","number":66,"title":"Created Table Components for Articles","url":"https://github.com/ucsb-cs156-w24/team03-w24-5pm-3/pull/66"},{"author":{"id":"MDQ6VXNlcjc5MzcxNjc1","is_bot":false,"login":"theanimated01","name":"Animesh Sachan"},"headRefName":"as-Articles-form","number":65,"title":"Created Form Components for Articles","url":"https://github.com/ucsb-cs156-w24/team03-w24-5pm-3/pull/65"}]
