
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-w24/team03-w24-5pm-3
owner: ucsb-cs156-w24
repo_name: team03-w24-5pm-3
pull_requests: [{"author":{"id":"U_kgDOBdHtDQ","is_bot":false,"login":"Shakcmpsc","name":""},"headRefName":"Yera-b","number":102,"title":"Copied Placeholders for UCSBOrganization pages; add to App.js/AppNavbar.js","url":"https://github.com/ucsb-cs156-w24/team03-w24-5pm-3/pull/102"},{"author":{"id":"U_kgDOBdYtJA","is_bot":false,"login":"bwr02","name":"Ben Richardson"},"headRefName":"ben-recrequest-index-page","number":101,"title":"Ben recrequest index page","url":"https://github.com/ucsb-cs156-w24/team03-w24-5pm-3/pull/101"},{"author":{"id":"MDQ6VXNlcjQ4MTI4MDUw","is_bot":false,"login":"bigjr-mkkong","name":"michael"},"headRefName":"michael-UCSBDiningCommonsMenuItem-placeholder","number":99,"title":"Copied placeholder and added App.js/AppNavbar.js","url":"https://github.com/ucsb-cs156-w24/team03-w24-5pm-3/pull/99"},{"author":{"id":"MDQ6VXNlcjQ4MTI4MDUw","is_bot":false,"login":"bigjr-mkkong","name":"michael"},"headRefName":"michael-UCSBDiningCommonsMenuItem-fixtures","number":98,"title":"added fixtures for ucsbDiningCommonsMenuItem","url":"https://github.com/ucsb-cs156-w24/team03-w24-5pm-3/pull/98"},{"author":{"id":"U_kgDOBdHtDQ","is_bot":false,"login":"Shakcmpsc","name":""},"headRefName":"Yera-a","number":82,"title":"Copied Placeholders for UCSBOrganization pages; add to App.js/AppNavbar.js","url":"https://github.com/ucsb-cs156-w24/team03-w24-5pm-3/pull/82"},{"author":{"id":"U_kgDOBdHtDQ","is_bot":false,"login":"Shakcmpsc","name":""},"headRefName":"Yera-table","number":81,"title":"Created Table for Organization","url":"https://github.com/ucsb-cs156-w24/team03-w24-5pm-3/pull/81"}]
