
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-w24/team03-w24-5pm-3
owner: ucsb-cs156-w24
repo_name: team03-w24-5pm-3
pull_requests: [{"author":{"id":"U_kgDOBdHK8A","is_bot":false,"login":"chloeqta","name":""},"headRefName":"ct-HelpRequest-backend","number":63,"title":"Copied files for Backend CRUD API HelpRequest from team02","url":"https://github.com/ucsb-cs156-w24/team03-w24-5pm-3/pull/63"},{"author":{"id":"MDQ6VXNlcjc5MzcxNjc1","is_bot":false,"login":"theanimated01","name":"Animesh Sachan"},"headRefName":"as-Articles-fixtures","number":62,"title":"Create fixtures for Articles","url":"https://github.com/ucsb-cs156-w24/team03-w24-5pm-3/pull/62"},{"author":{"id":"MDQ6VXNlcjc5MzcxNjc1","is_bot":false,"login":"theanimated01","name":"Animesh Sachan"},"headRefName":"as-Articles-backend","number":61,"title":"Copied files for Backend CRUD API Articles from team02","url":"https://github.com/ucsb-cs156-w24/team03-w24-5pm-3/pull/61"}]
