
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-w24/team03-w24-5pm-3
owner: ucsb-cs156-w24
repo_name: team03-w24-5pm-3
pull_requests: [{"author":{"id":"MDQ6VXNlcjQ4MTI4MDUw","is_bot":false,"login":"bigjr-mkkong","name":"michael"},"headRefName":"michael-UCSBDiningCommonsMenuItem-Edit","number":111,"title":"Michael ucsb dining commons menu item edit","url":"https://github.com/ucsb-cs156-w24/team03-w24-5pm-3/pull/111"},{"author":{"id":"MDQ6VXNlcjQ4MTI4MDUw","is_bot":false,"login":"bigjr-mkkong","name":"michael"},"headRefName":"michael-UCSBDiningCommonsMenuItem-index","number":110,"title":"Michael ucsb dining commons menu item index","url":"https://github.com/ucsb-cs156-w24/team03-w24-5pm-3/pull/110"},{"author":{"id":"MDQ6VXNlcjQ4MTI4MDUw","is_bot":false,"login":"bigjr-mkkong","name":"michael"},"headRefName":"michael-UCSBDiningCommonsMenuItem-CreatePage","number":106,"title":"Michael ucsb dining commons menu item create page","url":"https://github.com/ucsb-cs156-w24/team03-w24-5pm-3/pull/106"}]
