
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-w24/team03-w24-5pm-3
owner: ucsb-cs156-w24
repo_name: team03-w24-5pm-3
pull_requests: [{"author":{"id":"U_kgDOBdYtJA","is_bot":false,"login":"bwr02","name":"Ben Richardson"},"headRefName":"ben-Form-Component-RecRequest","number":89,"title":"added RecRequest Form","url":"https://github.com/ucsb-cs156-w24/team03-w24-5pm-3/pull/89"},{"author":{"id":"U_kgDOBdYtJA","is_bot":false,"login":"bwr02","name":"Ben Richardson"},"headRefName":"README-fixes-pt2","number":88,"title":"updated README.md","url":"https://github.com/ucsb-cs156-w24/team03-w24-5pm-3/pull/88"},{"author":{"id":"U_kgDOBdHK8A","is_bot":false,"login":"chloeqta","name":""},"headRefName":"ct-HelpRequest-placeholders","number":86,"title":"Copy Placeholders for HelpRequest pages; add to App.js/AppNavbar.js","url":"https://github.com/ucsb-cs156-w24/team03-w24-5pm-3/pull/86"},{"author":{"id":"U_kgDOBdHtDQ","is_bot":false,"login":"Shakcmpsc","name":""},"headRefName":"Yera-a","number":82,"title":"Copied Placeholders for UCSBOrganization pages; add to App.js/AppNavbar.js","url":"https://github.com/ucsb-cs156-w24/team03-w24-5pm-3/pull/82"},{"author":{"id":"U_kgDOBdHtDQ","is_bot":false,"login":"Shakcmpsc","name":""},"headRefName":"Yera-table","number":81,"title":"Created Table for Organization","url":"https://github.com/ucsb-cs156-w24/team03-w24-5pm-3/pull/81"},{"author":{"id":"U_kgDOBdHtDQ","is_bot":false,"login":"Shakcmpsc","name":""},"headRefName":"Yera-form","number":80,"title":"Completed Form","url":"https://github.com/ucsb-cs156-w24/team03-w24-5pm-3/pull/80"},{"author":{"id":"U_kgDOBXv56g","is_bot":false,"login":"sophiattran","name":""},"headRefName":"Sophia-MenuItemReviews-Pages","number":78,"title":"Sophia - Added MenuItemReview Placeholder pages","url":"https://github.com/ucsb-cs156-w24/team03-w24-5pm-3/pull/78"},{"author":{"id":"U_kgDOBXv56g","is_bot":false,"login":"sophiattran","name":""},"headRefName":"Sophia-MenuItemReviews-Table","number":77,"title":"Sophia - Implemented MenuItemReview Table component","url":"https://github.com/ucsb-cs156-w24/team03-w24-5pm-3/pull/77"},{"author":{"id":"U_kgDOBXv56g","is_bot":false,"login":"sophiattran","name":""},"headRefName":"Sophia-MenuItemReviews-Form","number":76,"title":"Sophia - Added MenuItemReviews Form plus tests","url":"https://github.com/ucsb-cs156-w24/team03-w24-5pm-3/pull/76"}]
